# Generated by Django 5.1.4 on 2025-09-13 11:55

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension("vector"),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rag_documents',
                'indexes': [models.Index(fields=['created_at'], name='rag_documen_created_10cac6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document')),
            ],
            options={
                'db_table': 'rag_document_chunks',
                'indexes': [models.Index(fields=['document'], name='rag_documen_documen_8ea7b8_idx')],
                'unique_together': {('document',)},
            },
        ),
    ]
